FROM nginx:stable-alpine

RUN apk --no-cache add \
        bash

COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

ENV USERNAME=username
ENV PASSWORD=password

COPY startup.sh /

CMD ["/startup.sh"]
